week4/exercises/auction_site/config/routes.rb
Rails.application.routes.draw do

  get '/' => 'site#home'

  resources :users, only: [:show, :create, :destroy, :new, :index] do
    resources :products, only: [:index, :show, :create, :destroy, :new]
  end

  get '/products' => 'products#index'

end

week4/exercises/auction_site/app/models/bid.rb
class Bid < ActiveRecord::Base
	validates :amount, presence: true
	belongs_to :product
	belongs_to :user
end

week4/exercises/auction_site/app/models/product.rb
class Product < ActiveRecord::Base
	validates :title, presence: true
	validates :description, presence: true
	validates :deadline, presence: true

	belongs_to :user
	has_many :bids, dependent: :destroy
end

week4/exercises/auction_site/app/models/user.rb
class User < ActiveRecord::Base
	validates :email, presence: true, uniqueness: true
	has_many :products, dependent: :destroy
	has_many :bids, dependent: :destroy
end

week4/exercises/auction_site/app/controllers/bids_controller.rb
class BidsController < ApplicationController
	def create
		
	end
end

week4/exercises/auction_site/app/controllers/products_controller.rb
class ProductsController < ApplicationController

	def index
		if params[:user_id]
			@user = User.find_by(id: params[:user_id])
			@products = @user.products.all
		else
			@products = Product.all
		end
	end

	def show
		@user = User.find_by(id: params[:user_id])
		@product = @user.products.find_by(id: params[:id])
		if @product
			render 'show'
		else
			render 'product_not_found'
		end
	end

	def create
		@user = User.find_by(id: params[:user_id])
		@product = @user.products.new(product_params)
		if @product.save
			redirect_to user_products_path(@user)
		else
			render 'new'
		end
	end

	def new
		@user = User.find_by(id: params[:user_id])
		@product = @user.products.new
	end

	def destroy
	end

	private #this says only the three arguments are allowed!
	def product_params
		params.require(:product).permit(:title, :description, :amount, :deadline)
	end
end

week4/exercises/auction_site/app/controllers/site_controller.rb
class SiteController < ApplicationController
  def home
  end
end

week4/exercises/auction_site/app/controllers/users_controller.rb
class UsersController < ApplicationController
	
	def index
		@users = User.all
			if @users.empty?
				render 'no_users'
			else
				render 'index'
		end
	end

	def show
		@user = User.find_by(id: params[:id])
		if @user
			render 'show'
		else
			render 'user_not_found'
		end
	end

	def create
		@user = User.create(user_params)
			if @user.save
				link_to user_path(@user)
			else
				render 'new'
			end
	end

	def destroy
		User.find(params[:id]).destroy
		redirect_to users_path
	end

	def new
		@user = User.new
	end
	
	private #this says only the three arguments are allowed!
	def user_params
		params.require(:user).permit(:name, :email)
	end
end

week4/exercises/auction_site/app/helpers/site_helper.rb
module SiteHelper
end

week4/exercises/auction_site/app/views/products/index.html.erb
<ul>
<% @products.each do |product| %>
	<li>
		<%= link_to("#{product.title}", user_product_path(product.user_id, product)) %>
		<br>
		<%= product.description %>
		<br>
		<%= product.deadline %>
		<br>
		<%= link_to("Destroy", user_product_path(product.user_id, product), method: :delete, data: { confirm: "Are you sure?"}) %>
		<br><br>
	</li>
<% end %>
</ul>

week4/exercises/auction_site/app/views/products/new.html.erb
<h1>List a new product!</h1>
<ul>
<% if @product.errors.any? %>
	<% @product.errors.full_messages.each do |error_msg| %>
		<li><%= error_msg %></li>
	<% end %>
<% end %>
</ul>

<%= form_for [@user, @product] do |f| %>

	<%= f.label :title %>
	<%= f.text_field :title %>
	<br>
	<%= f.label :description %>
	<%= f.text_area :description %>
	<br>
	<%= f.label :amount %>
	<%= f.number_field :amount %>
	<br>
	<%= f.label :deadline %>
	<%= f.datetime_local_field :deadline %>
	<br>
	<%= f.submit "Save" %>
	<br>
	<%= link_to("Cancel", users_path) %>
	<%= link_to("Home", "/") %>


<% end %>

week4/exercises/auction_site/app/views/products/product_not_found.html.erb
<h1>That product does not exist!</h1>

week4/exercises/auction_site/app/views/products/show.html.erb
<p><%= @product.title %></p>
<p><%= @product.description %></p>
<p><%= @product.amount %></p>
<p><%= @product.deadline %></p>
<br><br>
<%= link_to('Become a user', new_user_path) %>
<br>
<%= link_to('Home', '/') %>
<br><br>
<%= link_to("Destroy", user_product_path(@user, @product), method: :delete, data: { confirm: "Are you sure?"}) %>